### ISSUE TITLE
WinTV-NOVA-S2 drivers for debian buster

### ISSUE THREAD

**Issue by kj4qwt** [b-rad-NDi/Embedded-MediaDrivers#8]
Hello support,

Is there a way to build the debian kernel so that it will see the PCTV 461e device.
I have tried to build the linuxtv meditree without any success of the kernel being able to load or even look for the firmware.
I have tested the device on an unbuntu release just to make sure, and it works. Just wondering if installing it on debian is an option.

Kernel: 4.19.0-9-amd64
Release: Debian GNU/Linux 10 (buster)

Any help is much appreciated.

**Comment by b-rad-NDi** [comment]
This is the wrong repository to be filing an issue. This is for building drivers for embedded platforms and doesn't have anything to do with debian. The media_build system should build suitable drivers for you.
